# This class has ONE JOB ONLY:Play an audio file ( response generated by the LLM & STT (text) into audio ).

"""
Audio playback service for the AI Voice Assistant.
"""

from pathlib import Path
import logging

import pygame


logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)
from config.settings import TEMP_AUDIO_DIR

class PlayerService:
    """
    Service responsible for playing audio files.
    """

    def __init__(self):
        pygame.mixer.init()

    def play(self, audio_path: Path) -> None:
        """
        Play an audio file.

        Args:
            audio_path (Path):
                Path to the audio file.
        """

        if not audio_path.exists():
            raise FileNotFoundError(
                f"Audio file not found: {audio_path}"
            )

        logging.info(f"Playing: {audio_path.name}")

        pygame.mixer.music.load(str(audio_path))

        pygame.mixer.music.play()

        while pygame.mixer.music.get_busy():
            pygame.time.Clock().tick(10)

        logging.info("Playback completed.")

    def stop(self) -> None:
        """
        Stop the currently playing audio.
        """
        if pygame.mixer.get_init():
            pygame.mixer.music.stop()

if __name__ == "__main__":
    player = PlayerService()

    player.play(
        TEMP_AUDIO_DIR / "recording.wav"
    )
